[project]
name = "tidypyrs"
version = "0.5.2"
description = "Bring Tidyverse to Python with Polars backend"
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Longistamina", email = "dophamthelong03@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "polars>=1.44.1",
]
keywords = [
    "polars",
    "tidyverse",
    "dplyr",
    "dataframe",
    "data-science",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "numpy>=2.2.0",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "mkdocs-jupyter>=0.26.3",
    "mkdocs-material>=9.7.7",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.5",
]

[project.urls]
Homepage = "https://github.com/Longistamina/tidypyrs.git"
Repository = "https://github.com/Longistamina/tidypyrs.git"
Issues = "https://github.com/Longistamina/tidypyrs/issues"

[tool.ruff]
line-length = 200
